export const vocabularyMasterList = {
  // DAYS 1-5: The "Power" Words (Logic & Persuasion)
  "Day 1": ["Abnegation", "Alacrity", "Anachronistic", "Archetypal", "Ascetic", "Beguile", "Blandishment", "Cajole", "Callous", "Camaraderie", "Candor", "Capitulate", "Carouse", "Caucus", "Circumlocution", "Circumspect", "Cleave", "Cognizant", "Commensurate", "Complacency"],
  "Day 2": ["Concomitant", "Conduit", "Conflagration", "Congruity", "Connive", "Constituent", "Contravene", "Contrite", "Convivial", "Corpulence", "Covet", "Cupidity", "Dearth", "Debauch", "Decorous", "Demure", "Denigrate", "Deride", "Despot", "Diaphanous"],
  "Day 3": ["Didactic", "Diffident", "Disparate", "Disrepute", "Duplicity", "Ebullient", "Eclectic", "Edict", "Effrontery", "Effulgent", "Egregious", "Enervate", "Ephemeral", "Equanimity", "Equivocal", "Exculpate", "Execrable", "Exhort", "Exigent", "Expedient"],
  "Day 4": ["Expunge", "Extant", "Extol", "Fallacious", "Fatuous", "Feral", "Fetid", "Florid", "Fractious", "Garrulous", "Grandiloquence", "Gregarious", "Hackneyed", "Hapless", "Harangue", "Hegemony", "Iconoclast", "Idiosyncratic", "Impecunious", "Impetuous"],
  "Day 5": ["Impinge", "Implacable", "Inchoate", "Incontrovertible", "Ineffable", "Inexorable", "Ingenuous", "Inimical", "Iniquity", "Insidious", "Inure", "Invective", "Inveterate", "Jubilant", "Juxtaposition", "Laconic", "Languid", "Largess", "Latent", "Legerdemain"],

  // DAYS 6-10: Social Dynamics & Personality
  "Day 6": ["Licentious", "Lithe", "Malediction", "Malevolent", "Malleable", "Maxim", "Mendacious", "Modicum", "Morass", "Multifarious", "Munificent", "Nadir", "Neophyte", "Noisome", "Obdurate", "Obfuscate", "Obsequious", "Obstreperous", "Officious", "Ostensible"],
  "Day 7": ["Palliate", "Pallid", "Panacea", "Paradigm", "Paragon", "Pariah", "Parody", "Paucity", "Pejorative", "Pellucid", "Penchant", "Penurious", "Perfidious", "Perfunctory", "Permeate", "Perspicacity", "Pertinacious", "Petulance", "Platitude", "Plethora"],
  "Day 8": ["Portent", "Precocious", "Presage", "Prescient", "Probity", "Proclivity", "Promulgate", "Propensity", "Propitious", "Prosaic", "Prurient", "Puerile", "Pugnacious", "Pulchritude", "Punctilious", "Quagmire", "Querulous", "Quixotic", "Quotidian", "Recalcitrant"],
  "Day 9": ["Rectitude", "Redoubtable", "Refractory", "Reprobate", "Reprove", "Rescind", "Restive", "Ribald", "Rife", "Ruse", "Sacrosanct", "Sagacity", "Salient", "Sanctimonious", "Sanguine", "Scurrilous", "Serendipity", "Servile", "Solicitous", "Solipsism"],
  "Day 10": ["Spurious", "Staid", "Stolid", "Surfeit", "Surreptitious", "Sycophant", "Tacit", "Taciturn", "Tantamount", "Temerity", "Tenuous", "Timorous", "Torpid", "Tractable", "Transient", "Transmute", "Trenchant", "Truculent", "Turpitude", "Ubiquitous", "Umbrage"],

  // DAYS 11-20: Complexity, Science & Abstract Concepts
  "Day 11": ["Upbraid", "Utilitarian", "Vacillate", "Vacuous", "Vapid", "Variegated", "Venerable", "Veracity", "Vicarious", "Vicissitude", "Vilify", "Vituperate", "Vociferous", "Wallop", "Wallow", "Wane", "Wanton", "Wary", "Wily", "Wizened"],
  "Day 12": ["Zenith", "Zephyr", "Abjure", "Abrogate", "Acerbic", "Acrimony", "Adumbrate", "Ameliorate", "Anathema", "Antediluvian", "Apocryphal", "Apotheosis", "Arcane", "Asperity", "Assiduous", "Atrophy", "Augur", "Auspicious", "Austere", "Bellicose"],
  "Day 13": ["Benevolent", "Bourgeois", "Brusque", "Burnish", "Cache", "Cacophony", "Calumny", "Castigate", "Catharsis", "Chicanery", "Chimerical", "Churlish", "Clandestine", "Cloister", "Coalesce", "Coffer", "Cogent", "Collusion", "Complaisant", "Confluence"],
  "Day 14": ["Contentious", "Conundrum", "Credulity", "Cursory", "Debacle", "Debilitate", "Deference", "Delineate", "Demagogue", "Depravity", "Deprecate", "Desiccated", "Desultory", "Diatribe", "Dichotomy", "Dictum", "Diffident", "Digress", "Dilettante", "Discomfit"],
  "Day 15": ["Disparage", "Disseminate", "Dissonance", "Divisive", "Dogmatic", "Dour", "Ebullient", "Efficacy", "Effigy", "Elucidate", "Embroil", "Emulate", "Encomium", "Endemic", "Enervate", "Engender", "Enigma", "Ennui", "Ephemeral", "Equanimity"],
  "Day 16": ["Erudite", "Esoteric", "Euphemism", "Exacerbate", "Excoriate", "Exculpate", "Execrable", "Exegesis", "Exhort", "Exigent", "Exonerate", "Expatriate", "Expedient", "Expiate", "Expound", "Expunge", "Extemporaneous", "Extirpate", "Extol", "Extraneous"],
  "Day 17": ["Facetious", "Facilitate", "Fallacious", "Fastidious", "Fatuous", "Fawning", "Felicitous", "Fervid", "Fetid", "Fetter", "Fledgling", "Florid", "Flout", "Foment", "Forestall", "Fortuitous", "Fractious", "Frugality", "Fulminate", "Furtive"],
  "Day 18": ["Gainsay", "Garrulous", "Gibe", "Glower", "Goad", "Gossamer", "Gouge", "Grandiloquent", "Gregarious", "Grouse", "Guile", "Gullible", "Guy", "Halcyon", "Hallowed", "Harangue", "Harbinger", "Haughty", "Hegemony", "Hermetic"],
  "Day 19": ["Hierarchy", "Homogeneous", "Hyperbole", "Iconoclast", "Idolatry", "Immutable", "Impassive", "Impecunious", "Impede", "Impermeable", "Imperturbable", "Impervious", "Impetuous", "Implacable", "Implode", "Inadvertent", "Inchoate", "Incipient", "Incongruous", "Inconsequential"],
  "Day 20": ["Incorrigible", "Indefatigable", "Indigence", "Indolent", "Inert", "Ingenuous", "Inherent", "Innocuous", "Insensible", "Insinuate", "Insipid", "Insularity", "Intractable", "Intransigence", "Intrepid", "Inundate", "Inured", "Invective", "Irascible", "Irresolute"],
  
  // DAYS 21-25: Logic, Truth, and Deception
  "Day 21": ["Itinerant", "Jocose", "Labyrinthine", "Lassitude", "Levity", "Loquacious", "Lucid", "Luminous", "Magnanimity", "Maladroit", "Malleable", "Maverick", "Mellifluous", "Mendacity", "Meticulous", "Misanthrope", "Mitigate", "Mollify", "Morose", "Mundane"],
  "Day 22": ["Nefarious", "Neologism", "Nettle", "Nonchalant", "Obdurate", "Obsequious", "Obstinate", "Obviate", "Occlude", "Onerous", "Opaque", "Opprobrium", "Oscillation", "Ostentatious", "Paragon", "Partisan", "Pathological", "Paucity", "Pedantic", "Penchant"],
  "Day 23": ["Penury", "Perennial", "Perfidious", "Perfunctory", "Permeable", "Pervasive", "Phlegmatic", "Piety", "Placate", "Plasticity", "Platitude", "Plethora", "Plummet", "Pragmatic", "Preamble", "Precarity", "Precipitate", "Precursor", "Presumptuous", "Prevaricate"],
  "Day 24": ["Pristine", "Probity", "Problematic", "Prodigal", "Profound", "Proliferate", "Propitiate", "Propriety", "Proscribe", "Pungent", "Qualified", "Quibble", "Quiescent", "Rarefied", "Recalcitrant", "Recant", "Recondite", "Refractory", "Refute", "Relegate"],
  "Day 25": ["Reproach", "Reprobate", "Repudiate", "Rescind", "Resolution", "Reticent", "Reverent", "Sage", "Salubrious", "Sanction", "Satiate", "Saturate", "Savor", "Skeptical", "Solicitous", "Soporific", "Specious", "Spectrum", "Sporadic", "Stigma"],

  // DAYS 26-30: Human Character & Temperament
  "Day 26": ["Stint", "Stipulate", "Stolid", "Striated", "Strut", "Subpoena", "Subside", "Substantiate", "Supersede", "Supposition", "Tacit", "Taciturn", "Tangential", "Tenuous", "Tirade", "Torpor", "Tortuous", "Tractable", "Transgression", "Truculent"],
  "Day 27": ["Veneration", "Veracious", "Verbose", "Viable", "Viscous", "Vituperative", "Volatile", "Warranted", "Wary", "Welter", "Whimsical", "Zealot", "Abeyance", "Abscond", "Adulterate", "Aggrandize", "Alacrity", "Amalgamate", "Anachronism", "Analogous"],
  "Day 28": ["Anomalous", "Antipathy", "Apprise", "Approbation", "Appropriate", "Arduous", "Artless", "Ascetic", "Assuage", "Attenuate", "Audacious", "Austere", "Aver", "Banal", "Belie", "Beneficent", "Bombastic", "Boorish", "Burgeon", "Burnish"],
  "Day 29": ["Capricious", "Castigation", "Catalyst", "Caustic", "Chicanery", "Coagulate", "Coda", "Cogent", "Commensurate", "Compendium", "Complaisant", "Compliant", "Conciliatory", "Condone", "Confound", "Connoisseur", "Contention", "Contentious", "Contrite", "Conundrum"],
  "Day 30": ["Converge", "Convoluted", "Craven", "Daunt", "Decorum", "Default", "Deference", "Delineate", "Denigrate", "Deride", "Derivative", "Desiccate", "Desultory", "Deterrent", "Diatribe", "Dichotomy", "Diffidence", "Diffuse", "Digression", "Dirge"],

  // DAYS 31-35: Rhetoric & Professional Mastery
  "Day 31": ["Disabuse", "Discerning", "Discordant", "Discredit", "Discrepancy", "Discrete", "Disingenuous", "Disinterested", "Disjointed", "Dismiss", "Disparage", "Disparate", "Dissemble", "Disseminate", "Dissolution", "Dissonance", "Distend", "Distill", "Diverge", "Divest"],
  "Day 32": ["Dogmatic", "Dormant", "Dupe", "Ebullient", "Eclectic", "Efficacy", "Effrontery", "Elegy", "Elicit", "Eloquent", "Embellish", "Empirical", "Emulate", "Endemic", "Enervate", "Engender", "Enigma", "Enumerate", "Ephemeral", "Equanimity"],
  "Day 33": ["Equivocate", "Erudite", "Esoteric", "Eulogy", "Euphemism", "Exacerbate", "Exculpate", "Exigent", "Extemporaneous", "Facetious", "Facilitate", "Fallacious", "Fatuous", "Fawning", "Felicitous", "Fervid", "Flag", "Fledgling", "Flout", "Foment"],
  "Day 34": ["Forestall", "Frugality", "Futile", "Gainsay", "Garrulous", "Goad", "Gouge", "Grandiloquent", "Gregarious", "Guile", "Gullible", "Harangue", "Homogeneous", "Hyperbole", "Iconoclastic", "Idolatry", "Immutable", "Impair", "Impassive", "Impede"],
  "Day 35": ["Impermeable", "Imperturbable", "Impervious", "Implacable", "Implicit", "Implode", "Inadvertent", "Inchoate", "Incongruity", "Inconsequential", "Incorporate", "Indeterminate", "Indigence", "Indolent", "Inert", "Ingenuous", "Inherent", "Innocuous", "Insensible", "Insinuate"],

  // DAYS 36-40: The Subtle & The Abstract
  "Day 36": ["Insipid", "Insularity", "Intractable", "Intransigence", "Intrepid", "Inundate", "Inured", "Invective", "Irascible", "Irresolute", "Itinerary", "Judicious", "Lassitude", "Latency", "Laud", "Lethargic", "Levity", "Log", "Loquacious", "Lucid"],
  "Day 37": ["Luminous", "Magnanimity", "Malingerer", "Malleable", "Maverick", "Mendacious", "Metamorphosis", "Meticulous", "Misanthrope", "Mitigate", "Mollify", "Morose", "Mundane", "Nadir", "Neophyte", "Obdurate", "Obsequious", "Obstinate", "Obviate", "Occlude"],
  "Day 38": ["Onerous", "Opaque", "Opprobrium", "Oscillate", "Ostentatious", "Paragon", "Partisan", "Pathological", "Paucity", "Pedantic", "Penchant", "Penury", "Perennial", "Perfidious", "Perfunctory", "Permeable", "Pervasive", "Phlegmatic", "Piety", "Placate"],
  "Day 39": ["Plasticity", "Platitude", "Plethora", "Plummet", "Pragmatic", "Preamble", "Precipitate", "Precursor", "Presumptuous", "Prevaricate", "Pristine", "Probity", "Prodigal", "Profound", "Proliferate", "Propitiate", "Propriety", "Proscribe", "Pungent", "Qualified"],
  "Day 40": ["Quibble", "Quiescent", "Rarefied", "Recalcitrant", "Recant", "Recondite", "Refractory", "Refute", "Relegate", "Reproach", "Reprobate", "Repudiate", "Rescind", "Resolution", "Reticent", "Reverent", "Sage", "Salubrious", "Sanction", "Satiate"],

  // DAYS 41-45: Precision in Action and Speech
  "Day 41": ["Saturate", "Savor", "Secrete", "Shard", "Skeptical", "Solicitous", "Soporific", "Specious", "Spectrum", "Sporadic", "Stigma", "Stint", "Stipulate", "Stolid", "Striated", "Strut", "Subpoena", "Subside", "Substantiate", "Supersede"],
  "Day 42": ["Supposition", "Tacit", "Taciturn", "Tangential", "Tenuous", "Tirade", "Torpor", "Tortuous", "Tractable", "Transgression", "Truculent", "Vacillate", "Venerate", "Veracious", "Verbose", "Viable", "Viscous", "Vituperative", "Volatile", "Warranted"],
  "Day 43": ["Wary", "Welter", "Whimsical", "Zealot", "Abstain", "Adulterate", "Anomaly", "Apathy", "Assuage", "Audacious", "Capricious", "Corroborate", "Desiccate", "Enervate", "Ephemeral", "Equivocal", "Erudite", "Fervid", "Gullible", "Homogeneous"],
  "Day 44": ["Laconic", "Laudable", "Loquacious", "Lucid", "Mitigate", "Opaque", "Pedant", "Placate", "Pragmatic", "Precipitate", "Propriety", "Vacillate", "Volatile", "Zeal", "Abjure", "Abrogate", "Abstemious", "Acumen", "Antebellum", "Auspicous"],
  "Day 45": ["Belie", "Bellicose", "Bowdlerize", "Chicanery", "Churlish", "Circumlocution", "Circumnavigate", "Deciduous", "Deleterious", "Diffident", "Enervate", "Enfranchise", "Epiphany", "Equinox", "Euro", "Evanescent", "Expurgate", "Facetious", "Fatuous", "Feckless"],

  // DAYS 46-50: Intellectual and Cultural Nuance
  "Day 46": ["Fiduciary", "Filibuster", "Gauche", "Gerrymander", "Hegemony", "Homogeneous", "Hubris", "Hypotenuse", "Impeach", "Incognito", "Incontrovertible", "Inculcate", "Infrastructure", "Interpolate", "Irony", "Jejune", "Kowtow", "Laissez-faire", "Lexicon", "Loquacious"],
  "Day 47": ["Lugubrious", "Metamorphosis", "Mitosois", "Moiety", "Nanotechnology", "Nihilism", "Nomenclature", "Nonsectarian", "Notarize", "Obsequious", "Oligarchy", "Omnipotent", "Orthography", "Oxidize", "Paleontology", "Paradigm", "Parameter", "Pecuniary", "Photosynthesis", "Plagiarize"],
  "Day 48": ["Precipitous", "Quasar", "Quotidian", "Recapitulate", "Reciprocal", "Reparation", "Respiration", "Sanguine", "Soliloquy", "Subjugate", "Suffragist", "Supercilious", "Tautology", "Taxonomy", "Tectonic", "Tempestuous", "Thermodynamics", "Totalitarian", "Unctuous", "Usurp"],
  "Day 49": ["Vacuous", "Vehement", "Vortex", "Winnow", "Wrought", "Xenophobia", "Yeoman", "Ziggurat", "Abase", "Abeyance", "Abreast", "Abscission", "Abscond", "Abyss", "Accede", "Accretion", "Acerbic", "Acidulous", "Acme", "Actuary"],
  "Day 50": ["Adage", "Adduce", "Adroit", "Adulate", "Adulterate", "Adumbrate", "Aerie", "Aesthetic", "Affable", "Affected", "Aggrandize", "Agitate", "Alacrity", "Albeit", "Alienate", "Alloy", "Amalgamate", "Ambiguous", "Ambivalent", "Ameliorate"],

  // DAYS 51-55: Behavioral and Social Dynamics
  "Day 51": ["Amenable", "Amicable", "Amity", "Amorphous", "Anachronism", "Analgesic", "Analogous", "Anarchy", "Anathema", "Ancillary", "Animus", "Annul", "Anodyne", "Anomaly", "Antagonism", "Antediluvian", "Antipathy", "Antithetical", "Apace", "Apartheid"],
  "Day 52": ["Aphasia", "Aphorism", "Apocryphal", "Apostate", "Apostrophe", "Apotheosis", "Apparition", "Appease", "Appellation", "Apposite", "Apprise", "Approbation", "Appropriate", "Arbiter", "Arbitrary", "Arcane", "Archaic", "Archetype", "Ardor", "Arduous"],
  "Day 53": ["Argot", "Arraign", "Arrogant", "Arrogate", "Articulate", "Artifact", "Artless", "Ascendancy", "Ascetic", "Asperity", "Aspersion", "Assiduous", "Assimilate", "Assuage", "Astringent", "Asylum", "Atavism", "Atrophy", "Attenuate", "Attest"],
  "Day 54": ["Audacious", "Augment", "Augur", "August", "Aura", "Auspicious", "Austere", "Autocrat", "Autonomous", "Avarice", "Aver", "Averse", "Avid", "Avow", "Avuncular", "Axiom", "Babel", "Bacchanalian", "Bait", "Baleful"],
  "Day 55": ["Balk", "Ballast", "Banal", "Bane", "Banality", "Banter", "Bard", "Bask", "Bastion", "Bedlam", "Beguile", "Beholden", "Behoove", "Belabor", "Beleaguer", "Belie", "Belittle", "Bellicose", "Belligerent", "Bemoan"],

  // DAYS 56-60: Narrative and Descriptive Flair
  "Day 56": ["Benediction", "Benefactor", "Beneficent", "Benevolent", "Benign", "Berate", "Bereft", "Besiege", "Besmirch", "Bestial", "Bestow", "Betoken", "Bevy", "Bibliophile", "Bicker", "Biennial", "Bifurcate", "Bigot", "Bilious", "Bilk"],
  "Day 57": ["Bland", "Blandishment", "Blasphemy", "Blatant", "Bleak", "Blight", "Blithe", "Blunder", "Blunt", "Bluster", "Bohemian", "Boisterous", "Bolster", "Bombastic", "Boon", "Boor", "Bootless", "Boundless", "Bountiful", "Bourgeois"],
  "Day 58": ["Bovine", "Bowdlerize", "Boycott", "Braggart", "Brandish", "Brash", "Bravado", "Brawn", "Brazen", "Breach", "Brevity", "Brindled", "Bristle", "Brittle", "Broach", "Brooch", "Brook", "Browbeat", "Bruit", "Brunt"],
  "Day 59": ["Brusque", "Bucolic", "Buffoonery", "Bulwark", "Bungle", "Buoyant", "Bureaucracy", "Burgeon", "Burlesque", "Burnish", "Bustle", "Buttress", "Bylaw", "Byzantine", "Cabal", "Cache", "Cacophony", "Cadaverous", "Cadence", "Cadge"],
  "Day 60": ["Cajole", "Calamity", "Calculated", "Caldron", "Caliber", "Calligraphy", "Callous", "Callow", "Calumny", "Camaraderie", "Cameo", "Canard", "Candor", "Canker", "Canon", "Cant", "Cantankerous", "Canvass", "Capacious", "Capitulate"],

    // DAYS 61-65: Social Finesse & Power Dynamics
  "Day 61": ["Capricious", "Caption", "Captious", "Captivate", "Carat", "Cardinal", "Careen", "Caricature", "Carnage", "Carnal", "Carnivorous", "Carouse", "Carp", "Carrion", "Cartographer", "Cascade", "Caste", "Castigate", "Casualty", "Cataclysm"],
  "Day 62": ["Catalyst", "Catapult", "Cataract", "Catastrophe", "Categorical", "Catharsis", "Catholic", "Caucus", "Caustic", "Cauterize", "Cavalcade", "Cavalier", "Cavil", "Cede", "Celerity", "Celestial", "Celibate", "Censor", "Censorious", "Censure"],
  "Day 63": ["Centigrade", "Centrifugal", "Centripetal", "Centurion", "Cerebral", "Cerebration", "Ceremonious", "Certitude", "Cessation", "Cession", "Chafe", "Chaff", "Chagrin", "Chalice", "Chameleon", "Champion", "Chancellor", "Chaperon", "Charisma", "Charlatan"],
  "Day 64": ["Chary", "Chasm", "Chassis", "Chaste", "Chasten", "Chastise", "Chauvinist", "Checkered", "Cherubic", "Chicanery", "Chide", "Chimerical", "Chivalrous", "Choleric", "Choreography", "Chortle", "Chronic", "Chronicle", "Churlish", "Cipher"],
  "Day 65": ["Circuitous", "Circumlocution", "Circumscribe", "Circumspect", "Circumvent", "Cistern", "Citadel", "Cite", "Civil", "Clairvoyant", "Clamber", "Clamor", "Clandestine", "Clangor", "Clapper", "Clasp", "Claustrophobia", "Clavicle", "Cleave", "Cleft"],

  // DAYS 66-70: Subtle Differences & Textures
  "Day 66": ["Clemency", "Cliché", "Clientele", "Climax", "Clinch", "Cling", "Cloister", "Clout", "Cloy", "Clump", "Coagulate", "Coalesce", "Coalition", "Coda", "Coddle", "Codify", "Coercion", "Coeval", "Cog", "Cogent"],
  "Day 67": ["Cogitate", "Cognate", "Cognitive", "Cognizance", "Cohabit", "Coheir", "Cohere", "Cohesion", "Cohort", "Coiffure", "Coin", "Coincidence", "Colander", "Collaborate", "Collage", "Collate", "Collateral", "Collation", "Colloquial", "Colloquy"],
  "Day 68": ["Collusion", "Colossus", "Comatose", "Combustible", "Comely", "Comestible", "Comeuppance", "Comity", "Commandeer", "Commemorative", "Commensurate", "Commiserate", "Commodious", "Communal", "Compact", "Compassion", "Compatible", "Compelling", "Compendium", "Compensatory"],
  "Day 69": ["Compile", "Complacency", "Complaisant", "Complement", "Complementary", "Compliance", "Compliant", "Complicity", "Component", "Comport", "Composure", "Compound", "Comprehensive", "Compress", "Comprise", "Compromise", "Compulsion", "Compulsive", "Compulsory", "Compunction"],
  "Day 70": ["Compute", "Concatenate", "Concave", "Concede", "Conceit", "Concentric", "Conception", "Concerted", "Concession", "Conciliatory", "Concise", "Conclave", "Conclusive", "Concoct", "Concomitant", "Concord", "Concordance", "Concourse", "Concrete", "Concur"],

  // DAYS 71-80: Advanced Abstractions
  "Day 71": ["Condescend", "Condign", "Condiments", "Condole", "Condone", "Conducive", "Conduit", "Confidant", "Confide", "Confiscate", "Conflagration", "Confluence", "Conformity", "Confound", "Congeal", "Congenial", "Congenital", "Conglomerate", "Congregation", "Congruence"],
  "Day 72": ["Conifer", "Conjecture", "Conjugal", "Conjure", "Connivance", "Connoisseur", "Connotation", "Connubial", "Consanguine", "Conscientious", "Conscript", "Consecrate", "Consensus", "Consequential", "Conservatory", "Consign", "Consistency", "Console", "Consolidation", "Consonance"],
  "Day 73": ["Consort", "Conspicuous", "Conspiracy", "Constituent", "Constraint", "Construe", "Consummate", "Contagion", "Contaminate", "Contemn", "Context", "Contiguous", "Continence", "Contingent", "Contort", "Contraband", "Contravene", "Contrite", "Contrived", "Controversial"],
  "Day 74": ["Contumacious", "Contusion", "Conundrum", "Convene", "Convention", "Converge", "Conversant", "Converse", "Convert", "Convex", "Conveyance", "Conviction", "Convivial", "Convoke", "Convoluted", "Copious", "Coquette", "Cordial", "Cordon", "Cornucopia"],
  "Day 75": ["Corollary", "Coronation", "Corporeal", "Corpulent", "Correlation", "Corroborate", "Corrode", "Corrosive", "Corrugated", "Cosmopolitan", "Coterie", "Countenance", "Countermand", "Counterpart", "Coup", "Couple", "Courier", "Covenant", "Covert", "Covetous"],
  "Day 76": ["Cower", "Coy", "Cozen", "Crabbed", "Crafty", "Crass", "Craven", "Credence", "Credenda", "Credential", "Credibility", "Credo", "Credulity", "Creed", "Crescendo", "Crestfallen", "Crevice", "Cringe", "Criteria", "Crone"],
  "Day 77": ["Crotchety", "Crucial", "Crucible", "Crux", "Cryptic", "Cubicle", "Cuisine", "Culinary", "Cull", "Culminate", "Culpable", "Culprit", "Culvert", "Cumbersome", "Cumulative", "Cupidity", "Curator", "Curmudgeon", "Cursive", "Cursory"],
  "Day 78": ["Curt", "Curtail", "Cynic", "Cynosure", "Dabble", "Dais", "Dally", "Dank", "Dapper", "Dappled", "Daub", "Daunt", "Dauntless", "Dawdle", "Deadlock", "Deadpan", "Dearth", "Debacle", "Debase", "Debauch"],
  "Day 79": ["Debilitate", "Debonair", "Debris", "Debunk", "Debutante", "Decadence", "Decant", "Decapitate", "Decelerate", "Deciduous", "Decimate", "Decipher", "Declivity", "Décolleté", "Decomposition", "Decorate", "Decorous", "Decorum", "Decoy", "Decrepitude"],
  "Day 80": ["Decry", "Deduce", "Deface", "Defalcate", "Defamation", "Default", "Defeatist", "Defection", "Defer", "Deference", "Defiance", "Defile", "Definitive", "Deflect", "Defoliate", "Defray", "Deft", "Defunct", "Degenerate", "Degradation"],

  // DAYS 81-90: The Final Push (Rhetoric & Obscurity)
  "Day 81": ["Deify", "Deign", "Delectable", "Delegate", "Deleterious", "Deliberate", "Delineate", "Delirium", "Delude", "Deluge", "Delusion", "Delve", "Demagogue", "Demean", "Demeanor", "Demented", "Demerit", "Demise", "Demolition", "Demoniac"],
  "Day 82": ["Demur", "Demure", "Denigrate", "Denizen", "Denotation", "Denouement", "Denounce", "Depict", "Deplete", "Deplore", "Deploy", "Depose", "Deposition", "Depravity", "Deprecate", "Depreciate", "Depredation", "Deprive", "Derelict", "Deride"],
  "Day 83": ["Derivative", "Dermatologist", "Derogatory", "Descant", "Descry", "Desecrate", "Desiccate", "Desideratum", "Designate", "Desist", "Desolate", "Desperado", "Despicable", "Despise", "Despoil", "Despondent", "Despot", "Destitute", "Desultory", "Detached"],
  "Day 84": ["Detergent", "Deteriorate", "Determinant", "Deterrent", "Detonation", "Detraction", "Detrimental", "Deviate", "Devious", "Devise", "Devoid", "Devolve", "Devotee", "Devout", "Dexterous", "Diabolical", "Diadem", "Dialectic", "Diaphanous", "Diatribe"],
  "Day 85": ["Dichotomy", "Dictum", "Didactic", "Die", "Diffidence", "Diffuse", "Digression", "Dilapidated", "Dilate", "Dilatory", "Dilemma", "Dilettante", "Diligent", "Dilute", "Diminution", "Din", "Dingy", "Dint", "Diorama", "Dire"],
  "Day 86": ["Dirge", "Disabuse", "Disaffected", "Disagreeable", "Disallow", "Disannul", "Disarray", "Disarticulate", "Disassemble", "Disassociate", "Disaster", "Disavow", "Disband", "Disbar", "Disbelieve", "Disburden", "Disburse", "Discard", "Discern", "Discharge"],
  "Day 87": ["Disciple", "Disclaim", "Disclose", "Discolor", "Discomfit", "Discomfort", "Discompose", "Disconcert", "Disconnect", "Disconsolate", "Discontent", "Discontinue", "Discord", "Discount", "Discourage", "Discourse", "Discourteous", "Discover", "Discredit", "Discreet"],
  "Day 88": ["Discrepancy", "Discrete", "Discretion", "Discriminate", "Discursive", "Disdain", "Disease", "Disembark", "Disembody", "Disenchant", "Disencumber", "Disengage", "Disentangle", "Disfigure", "Disfranchise", "Disgorge", "Disgrace", "Disgruntle", "Disguise", "Disgust"],
  "Day 89": ["Dishearten", "Disheveled", "Dishonor", "Disillusion", "Disinclination", "Disinfect", "Disingenuous", "Disinherit", "Disintegrate", "Disinter", "Disinterested", "Disjoin", "Disjointed", "Dislocate", "Dislodge", "Disloyal", "Dismal", "Dismantle", "Dismay", "Dismember"],
  "Day 90": ["Dismiss", "Dismount", "Disobedience", "Disobey", "Disorder", "Disorganize", "Disorient", "Disown", "Disparage", "Disparate", "Disparity", "Dispassionate", "Dispatch", "Dispel", "Dispensable", "Dispense", "Disperse", "Dispirit", "Displace", "Display"]
};